const { Router } = require("express");

module.exports.isLoggedIn = (req, res, next) => {
//YPU WILL ALWAYS GET USER INFO IF HE IS LOGGED IN
//FROM THE COOKIES SESSION


//YOU MIGHT HAVE OBSERVED WHEN YOU TRY TO DO EDIT PAGE 
//WITH OUT LOGGIN IT WILL REDIRECT TO LOGGIN PAGE
//BUT ONCE YOU LOGGIN THEN IT DOESNT TAKE YOU BACK TO EDIT
//INORDER TO DO THIS WE NEED TO SEE WHAT ROUTE THE USER WAS TRYING TO ACCESS
//AND  THAT CAN BE GOT IN REQ.ORIGINAL URL TRY TO PRINT YOU WILL GET IT
//AND WE ARE STORING IT IN PASSPORTS SESSION SO THAT WHEN GOING TO OTHER PAGE YOU NEED TO SAVE SOMEWHERE

req.session.redirectUrl=req.originalUrl;
//BUT ABOVE HAS ONE PROBLEM
//PASSPORT AFTER LOGGIN WILL DELETE SESSION SO IT WONT BE ACCESSEBLE
//FOR THIS YOU STORE IT IN REQ.LOCALS
//CHACK NECT MIDDLEWARE WHERE WE ARE STORING IT
    console.log(req.user);
    if (!req.isAuthenticated()) {
        req.flash("ERROR", "Please login")
        return res.redirect("/login");
    }
    next();
}

module.exports.saveRedirectUrl=(req,res,next)=>{
//CHECK ABOVE MDW COMMENT
//IF WE HAVE SESSION DATA THEN STORE IN LOCAL
//YOU WILL USE THIS MDW WHILE LOGIN Router//CHECK LOGIN ROUTE
    if(req.session.redirectUrl)
    {
        res.locals.redirectUrl=req.session.redirectUrl;
    }
    next();
}